---
title: "decontam"
author: "Francisca Rodriguez"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#############################################################################
################ DECONTAMINATE CONTROLS #####################################
#############################################################################

#remove ASVs with only one read 
ps <- prune_taxa(taxa_sums(ps) > 1, ps)
ps

#look at the library sizes of the controls and samples
df <- as.data.frame(sample_data(ps)) # Put sample_data into a ggplot-friendly data.frame
df$LibrarySize <- sample_sums(ps)
df <- df[order(df$LibrarySize),]
df$Index <- seq(nrow(df))
ggplot(data=df, aes(x=Index, y=LibrarySize, color=Sample_or_Control)) + geom_point()

#label controls (extraction negatives) and clean
sample_data(ps)$is.neg <- sample_data(ps)$Sample_or_Control == "Control"
contams <- isContaminant(ps, method="prevalence", neg="is.neg")
table(contams$contaminant)

#Remove contaminants
ps.noncontam <- prune_taxa(!contams$contaminant, ps)
ps.noncontam

```


```{r}
##POST INOC PRE STRESS ######################################################

#post_inoc_pre_stress table 
post_inoc_pre_stress_ps <- subset_samples(ps.noncontam, sample_data(ps.noncontam)$SampleType=="post_inoc_pre_stress")

##label post_inoc_pre_stress by inoculation
post_inoc_pre_stress_i1 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "1")
  post_inoc_pre_stress_i1 <- as.data.frame(otu_table(post_inoc_pre_stress_i1))
  
post_inoc_pre_stress_i2 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "2")
  post_inoc_pre_stress_i2 <- as.data.frame(otu_table(post_inoc_pre_stress_i2))
  
post_inoc_pre_stress_i3 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "3")
  post_inoc_pre_stress_i3 <- as.data.frame(otu_table(post_inoc_pre_stress_i3))
  
post_inoc_pre_stress_i4 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "4")
  post_inoc_pre_stress_i4 <- as.data.frame(otu_table(post_inoc_pre_stress_i4))
  
post_inoc_pre_stress_i5 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "5")
  post_inoc_pre_stress_i5 <- as.data.frame(otu_table(post_inoc_pre_stress_i5))

````

```{r}
##POST INOC POST STRESS#####################################################

#post_inoc_post_stress table 
post_inoc_post_stress_ps <- subset_samples(ps.noncontam, sample_data(ps.noncontam)$SampleType=="post_inoc_post_stress")

##label post_inoc_post_stress by inoculation x water treatment

#inoculation 1 
post_inoc_post_stress_i1_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i1_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w1))

post_inoc_post_stress_i1_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i1_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w2))

post_inoc_post_stress_i1_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i1_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w3))

#inoculation 2
post_inoc_post_stress_i2_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i2_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w1))

post_inoc_post_stress_i2_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i2_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w2))

post_inoc_post_stress_i2_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i2_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w3))

#inoculation 3
post_inoc_post_stress_i3_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i3_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w1))

post_inoc_post_stress_i3_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i3_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w2))

post_inoc_post_stress_i3_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i3_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w3))

#inoculation 4
post_inoc_post_stress_i4_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i4_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w1))

post_inoc_post_stress_i4_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i4_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w2))

post_inoc_post_stress_i4_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i4_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w3))

#inoculation 5
post_inoc_post_stress_i5_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i5_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w1))

post_inoc_post_stress_i5_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i5_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w2))

post_inoc_post_stress_i5_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i5_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w3))

```
