---
title: "4_treatment_ASV_overlap"
author: "Francisca Rodriguez"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#############################################################################
################### PRE-DECONTAM ############################################
#############################################################################

library(phyloseq)

#load data
pre_inoc_ps <- readRDS("./intermediate_data/pre_inoc_ps.rds")
slurry_ps <- readRDS("./intermediate_data/slurry_ps.rds")
DNA_PCR_neg_ps <- readRDS("./intermediate_data/DNA_PCR_neg_ps.rds")
di_water_ps <- readRDS("./intermediate_data/di_water_ps.rds")
i6_ps <- readRDS("./intermediate_data/i6_ps.rds")
post_inoc_pre_stress_ps <- readRDS("./intermediate_data/post_inoc_pre_stress_ps.rds")
post_inoc_post_stress_ps <- readRDS("./intermediate_data/post_inoc_post_stress_ps.rds")

```

```{r}
#############################################################################
####REMOVE ASVS WITH ONLY 1 READ / ADD NAMES TO ASV TABLES  #################
#############################################################################

##DNA PCR NEG####
DNA_PCR_neg_ps <- prune_taxa(taxa_sums(DNA_PCR_neg_ps) > 1, DNA_PCR_neg_ps) #get rid of zeroes
DNA_PCR_neg_names <- paste("DNA_PCR_neg_", sprintf('%0.4d', 1:length(sample_names(DNA_PCR_neg_ps))), sep = "") # generate the row names 
sample_names(DNA_PCR_neg_ps) <- DNA_PCR_neg_names # reassign the names from the sequences to the generated sample names
DNA_PCR_neg_asv <- as.data.frame(otu_table(DNA_PCR_neg_ps)) #create asv table

##DI WATER#############
di_water_ps <- prune_taxa(taxa_sums(di_water_ps) > 1, di_water_ps)
di_water_names <- paste("di_water_", sprintf('%0.4d', 1:length(sample_names(di_water_ps))), sep = "") 
sample_names(di_water_ps) <- di_water_names
di_water_asv <- as.data.frame(otu_table(di_water_ps))

##INOCULATION 6 - H2O CONTROL#############
i6_ps <- prune_taxa(taxa_sums(i6_ps) > 1, i6_ps)
i6_names <- paste("i6_", sprintf('%0.4d', 1:length(sample_names(i6_ps))), sep = "") 
sample_names(i6_ps) <- i6_names
i6_asv <- as.data.frame(otu_table(i6_ps))

##PRE INOC########
pre_inoc_ps <- prune_taxa(taxa_sums(pre_inoc_ps) > 1, pre_inoc_ps)
pre_inoc_names <- paste("pre_inoc_", sprintf('%0.4d', 1:length(sample_names(pre_inoc_ps))), sep = "") 
sample_names(pre_inoc_ps) <- pre_inoc_names
pre_inoc_asv <- as.data.frame(otu_table(pre_inoc_ps))

##SLURRY#########
slurry_names <- paste("slurry_", sprintf('%0.4d', 1:length(sample_names(slurry_ps))), sep = "")
sample_names(slurry_ps) <- slurry_names 
slurry_asv <- as.data.frame(otu_table(slurry_ps))

##POST INOC PRE STRESS#####
post_inoc_pre_stress_names <- paste("post_inoc_pre_stress_", sprintf('%0.4d', 1:length(sample_names(post_inoc_pre_stress_ps))), sep = "")
sample_names(post_inoc_pre_stress_ps) <- post_inoc_pre_stress_names
post_inoc_pre_stress_asv <- as.data.frame(otu_table(post_inoc_pre_stress_ps))

##POST INOC POST STRESS####
post_inoc_post_stress_names <- paste("post_inoc_post_stress_", sprintf('%0.4d', 1:length(sample_names(post_inoc_post_stress_ps))), sep = "")
sample_names(post_inoc_post_stress_ps) <- post_inoc_post_stress_names
post_inoc_post_stress_asv <- as.data.frame(otu_table(post_inoc_post_stress_ps)) 

```


```{r}
## COMBINE ASV TABLES ##

#create control ASV table
control_asvs <- dplyr::bind_rows(DNA_PCR_neg_asv, di_water_asv, i6_asv, pre_inoc_asv)

#obtain a list of all the columns in that data frame
asvs <- colnames(control_asvs)

#filter for ASVs present in controls
edited_slurry <- slurry_asv[,asvs]
edited_postinocprestress <- post_inoc_pre_stress_asv[,asvs]
edited_postinocpoststress <- post_inoc_post_stress_asv[,asvs]

#combine data frames
comboASVs <- dplyr::bind_rows(control_asvs, edited_slurry, edited_postinocprestress, edited_postinocpoststress)

#export as .csv
controlASVs <-  write.csv(comboASVs, "./output/controlASVs.csv")

##DETERMINE TOTAL READS FROM TREATMENT ####
totalTreatmentReads <- rowSums(post_inoc_post_stress_asv)
treatmentASVs <- write.csv(totalTreatmentReads, "./output/treatmentASVs.csv")

```