---
title: "alpha_beta_diversity_curves"
author: "Francisca Rodriguez"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#############################################################################
##################### POST-DECONTAM  ########################################
#############################################################################

#load libraries / data
library(phyloseq)
library(ggplot2)
library(decontam)
library(vegan)

ps.noncontam <- readRDS("./intermediate_data/ps.noncontam.rds")

```

```{r}
##SUBSET POST INOC PRE STRESS ######################################################

#post_inoc_pre_stress table 
post_inoc_pre_stress_ps <- subset_samples(ps.noncontam, sample_data(ps.noncontam)$SampleType=="post_inoc_pre_stress")

##label post_inoc_pre_stress by inoculation
post_inoc_pre_stress_i1 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "1")
  post_inoc_pre_stress_i1 <- as.data.frame(otu_table(post_inoc_pre_stress_i1))
  
post_inoc_pre_stress_i2 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "2")
  post_inoc_pre_stress_i2 <- as.data.frame(otu_table(post_inoc_pre_stress_i2))
  
post_inoc_pre_stress_i3 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "3")
  post_inoc_pre_stress_i3 <- as.data.frame(otu_table(post_inoc_pre_stress_i3))
  
post_inoc_pre_stress_i4 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "4")
  post_inoc_pre_stress_i4 <- as.data.frame(otu_table(post_inoc_pre_stress_i4))
  
post_inoc_pre_stress_i5 <- subset_samples(post_inoc_pre_stress_ps, sample_data(post_inoc_pre_stress_ps)$Inoculation == "5")
  post_inoc_pre_stress_i5 <- as.data.frame(otu_table(post_inoc_pre_stress_i5))

```

```{r}
##SUBSET POST INOC POST STRESS#####################################################

#post_inoc_post_stress table 
post_inoc_post_stress_ps <- subset_samples(ps.noncontam, sample_data(ps.noncontam)$SampleType=="post_inoc_post_stress")

##label post_inoc_post_stress by inoculation x water treatment

#inoculation 1 
post_inoc_post_stress_i1_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i1_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w1))

post_inoc_post_stress_i1_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i1_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w2))

post_inoc_post_stress_i1_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "1" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i1_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i1_w3))

#inoculation 2
post_inoc_post_stress_i2_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i2_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w1))

post_inoc_post_stress_i2_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i2_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w2))

post_inoc_post_stress_i2_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "2" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i2_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i2_w3))

#inoculation 3
post_inoc_post_stress_i3_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i3_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w1))

post_inoc_post_stress_i3_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i3_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w2))

post_inoc_post_stress_i3_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "3" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i3_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i3_w3))

#inoculation 4
post_inoc_post_stress_i4_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i4_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w1))

post_inoc_post_stress_i4_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i4_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w2))

post_inoc_post_stress_i4_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "4" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i4_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i4_w3))

#inoculation 5
post_inoc_post_stress_i5_w1 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "1")
  post_inoc_post_stress_i5_w1 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w1))

post_inoc_post_stress_i5_w2 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "2")
  post_inoc_post_stress_i5_w2 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w2))

post_inoc_post_stress_i5_w3 <- subset_samples(post_inoc_post_stress_ps, sample_data(post_inoc_post_stress_ps)$Inoculation == "5" & sample_data(post_inoc_post_stress_ps)$Water == "3")
  post_inoc_post_stress_i5_w3 <- as.data.frame(otu_table(post_inoc_post_stress_i5_w3))

```


```{r}
#############################################################################
######## SPECIES ACCUMULATION CURVES (BETA DIVERSITY)  ######################
#############################################################################
  
par(mfrow=c(4,5))

##POST INOC PRE STRESS #####################################################
accurve_prei1 <- specaccum(post_inoc_pre_stress_i1, method = "random", permutations = 400)
plot(accurve_prei1$sites, accurve_prei1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc pre-stress ASVs - Inoculation 1")

accurve_prei2 <- specaccum(post_inoc_pre_stress_i2, method = "random", permutations = 400)
plot(accurve_prei2$sites, accurve_prei2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc pre-stress ASVs - Inoculation 2")

accurve_prei3 <- specaccum(post_inoc_pre_stress_i3, method = "random", permutations = 400)
plot(accurve_prei3$sites, accurve_prei3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc pre-stress ASVs - Inoculation 3")

accurve_prei4 <- specaccum(post_inoc_pre_stress_i4, method = "random", permutations = 400)
plot(accurve_prei4$sites, accurve_prei4$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc pre-stress ASVs - Inoculation 4")

accurve_prei5 <- specaccum(post_inoc_pre_stress_i5, method = "random", permutations = 400)
plot(accurve_prei5$sites, accurve_prei5$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc pre-stress ASVs - Inoculation 5")


##POST INOC POST STRESS #####################################################

accurve_posti1w1 <- specaccum(post_inoc_post_stress_i1_w1, method = "random", permutations = 400)
plot(accurve_posti1w1$sites, accurve_posti1w1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i1 x w1")

accurve_posti1w2 <- specaccum(post_inoc_post_stress_i1_w2, method = "random", permutations = 400)
plot(accurve_posti1w2$sites, accurve_posti1w2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i1 x w2")

accurve_posti1w3 <- specaccum(post_inoc_post_stress_i1_w3, method = "random", permutations = 400)
plot(accurve_posti1w3$sites, accurve_posti1w3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i1 x w3")

accurve_posti2w1 <- specaccum(post_inoc_post_stress_i2_w1, method = "random", permutations = 400)
plot(accurve_posti2w1$sites, accurve_posti2w1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i2 x w1")

accurve_posti2w2 <- specaccum(post_inoc_post_stress_i2_w2, method = "random", permutations = 400)
plot(accurve_posti2w2$sites, accurve_posti2w2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i2 x w2")

accurve_posti2w3 <- specaccum(post_inoc_post_stress_i2_w3, method = "random", permutations = 400)
plot(accurve_posti2w3$sites, accurve_posti2w3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i2 x w3")

accurve_posti3w1 <- specaccum(post_inoc_post_stress_i3_w1, method = "random", permutations = 400)
plot(accurve_posti3w1$sites, accurve_posti3w1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i3 x w1")

accurve_posti3w2 <- specaccum(post_inoc_post_stress_i3_w2, method = "random", permutations = 400)
plot(accurve_posti3w2$sites, accurve_posti3w2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i3 x w2")

accurve_posti3w3 <- specaccum(post_inoc_post_stress_i3_w3, method = "random", permutations = 400)
plot(accurve_posti3w3$sites, accurve_posti3w3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i3 x w3")

accurve_posti4w1 <- specaccum(post_inoc_post_stress_i4_w1, method = "random", permutations = 400)
plot(accurve_posti4w1$sites, accurve_posti4w1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i4 x w1")

accurve_posti4w2 <- specaccum(post_inoc_post_stress_i4_w2, method = "random", permutations = 400)
plot(accurve_posti4w2$sites, accurve_posti4w2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress - i4 x w2")

accurve_posti4w3 <- specaccum(post_inoc_post_stress_i4_w3, method = "random", permutations = 400)
plot(accurve_posti4w3$sites, accurve_posti4w3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress - i4 x w3")

accurve_posti5w1 <- specaccum(post_inoc_post_stress_i5_w1, method = "random", permutations = 400)
plot(accurve_posti5w1$sites, accurve_posti5w1$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i5 x w1")

accurve_posti5w2 <- specaccum(post_inoc_post_stress_i5_w2, method = "random", permutations = 400)
plot(accurve_posti5w2$sites, accurve_posti5w2$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i5 x w2")

accurve_posti5w3 <- specaccum(post_inoc_post_stress_i5_w3, method = "random", permutations = 400)
plot(accurve_posti5w3$sites, accurve_posti5w3$richness,
     xlab = "Number of sample",
     ylab = "Species richness",
     main = "Post-inoc post-stress ASVs - i5 x w3")

```


```{r}

#############################################################################
################ SEQ DEPTH CURVES (ALPHA DIVERSITY)  ########################
#############################################################################

par(mfrow=c(4,5))

##POST INOC PRE STRESS#######################################################

#post_inoc_pre_stress_i1
rarecurve(post_inoc_pre_stress_i1,
          step = 1, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc pre-stress ASVs - Inoculation 1")

#post_inoc_pre_stress_i2
rarecurve(post_inoc_pre_stress_i2, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc pre-stress ASVs - Inoculation 2")

#post_inoc_pre_stress_i3
rarecurve(post_inoc_pre_stress_i3, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size",
          ylab = "ASV", 
          main = "Post-inoc pre-stress ASVs - Inoculation 3")

#post_inoc_pre_stress_i4
rarecurve(post_inoc_pre_stress_i4, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc pre-stress ASVs - Inoculation 4")

#post_inoc_pre_stress_i5
rarecurve(post_inoc_pre_stress_i5, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc pre-stress ASVs - Inoculation 5")

##POST INOC POST STRESS#######################################################

##INOCULATION 1
#post_inoc_post_stress_i1_w1
rarecurve(post_inoc_post_stress_i1_w1, 
          step = 20,
          label = FALSE,
          col = "blue", 
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i1 x w1")

#post_inoc_post_stress_i1_w2
rarecurve(post_inoc_post_stress_i1_w2, 
          step = 20, 
          col = "blue",
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i1 x w2")

#post_inoc_post_stress_i1_w3
rarecurve(post_inoc_post_stress_i1_w3, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i1 x w3")

##INOCULATION 2
#post_inoc_post_stress_i2_w1
rarecurve(post_inoc_post_stress_i2_w1, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i2 x w1")

#post_inoc_post_stress_i2_w2
rarecurve(post_inoc_post_stress_i2_w2, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i2 x w2")

#post_inoc_post_stress_i2_w3
rarecurve(post_inoc_post_stress_i2_w3, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i2 x w3")

##INOCULATION 3
#post_inoc_post_stress_i3_w1
rarecurve(post_inoc_post_stress_i3_w1, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i3 x w1")

#post_inoc_post_stress_i3_w2
rarecurve(post_inoc_post_stress_i3_w2, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i3 x w2")

#post_inoc_post_stress_i3_w3
rarecurve(post_inoc_post_stress_i3_w3, 
          step = 20, 
          col = "blue", 
          cex = 0.6, 
          label = FALSE,
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i3 x w3")

##INOCULATION 4
#post_inoc_post_stress_i4_w1
rarecurve(post_inoc_post_stress_i4_w1, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i4 x w1")

#post_inoc_post_stress_i4_w2
rarecurve(post_inoc_post_stress_i4_w2, 
          step = 20, 
          col = "blue", 
          cex = 0.6, 
          label = FALSE,
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i4 x w2")

#post_inoc_post_stress_i4_w3
rarecurve(post_inoc_post_stress_i4_w3, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i4 x w3")


##INOCULATION 5 
#post_inoc_post_stress_i5_w1
rarecurve(post_inoc_post_stress_i5_w1, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i5 x w1")

#post_inoc_post_stress_i5_w2
rarecurve(post_inoc_post_stress_i5_w2, 
          step = 20, 
          col = "blue", 
          cex = 0.6, 
          label = FALSE,
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i5 x w2")

#post_inoc_post_stress_i5_w3
rarecurve(post_inoc_post_stress_i5_w3, 
          step = 20, 
          col = "blue", 
          label = FALSE,
          cex = 0.6, 
          xlab = "Sample Size", 
          ylab = "ASV", 
          main = "Post-inoc post-stress ASVs - i5 x w3")

```