---
title: "ANOVA"
author: "Francisca Rodriguez"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#############################################################################
################  POST-DECONTAM #############################################
#############################################################################

library(tidyverse)
library(car)
library(ggpubr)
library(effects)

dat = read_csv("./pips_data/pips_complete.csv") |>
  mutate(
    Inoculation = as.character(Inoculation),
    Water = as.character(Water)
  )

ggplot(dat, aes(Inoculation, SpeciesRichness, fill = Water)) +
  facet_wrap(~ Type) +
  scale_y_log10() +
  geom_boxplot()

```

```{r}
## OUTLIER ANALYSIS ##

### SPECIES RICHNESS: ROOTS + SHOOTS ########################################

# interaction model
fit1 = aov(log(SpeciesRichness) ~ Type + Inoculation * Water, data = dat)
Anova(fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate

# additive model
fit2 = aov(log(SpeciesRichness) ~ Type + Inoculation + Water, data = dat)
Anova(fit2, type = "2") # if you don't have interactions, type-2 sums-of-squares is appropriate

#plot to check residuals
plot(fit1)
plot(fit2)

# Studentized residuals
MASS::studres(fit1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_dat = dat[-c(401, 78, 34, 81, 123), ]

```


```{r}
## ANOVA ##

## SPECIES RICHNESS: COMBINED ROOTS AND SHOOTS W/FILTERED DATA ########################

#interaction model
filtered_fit1 = aov(log(SpeciesRichness) ~ Type + Inoculation * Water, data = filtered_dat)
Anova(filtered_fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(filtered_fit1)

#additive model 
filtered_fit2 = aov(log(SpeciesRichness) ~ Type + Inoculation + Water, data = filtered_dat)
Anova(filtered_fit2, type = "2")
plot(filtered_fit2)

#check the outliers again
shapiro.test(filtered_fit1$residuals)
leveneTest(log(SpeciesRichness) ~ Water, data = dat[-c(401, 78, 34, 81, 123), ])

filtered_dat = filtered_dat |>
  mutate(res = resid(filtered_fit1))

#plot the filtered data to check the spread
ggplot(filtered_dat, aes(log(SpeciesRichness))) +
  facet_grid(Water ~ Inoculation) +
  # scale_x_log10() +
  geom_histogram()

#Re-plot grouped boxplot by inoculation and plant part without the outliers
ggplot(filtered_dat, aes(x=Inoculation, y=SpeciesRichness, fill=Water)) + 
    geom_boxplot() + theme_light() + facet_wrap(~ Type)

```


```{r}
## ANOVA ##

## SPECIES RICHNESS: ROOTS ###################################################

root_dat = subset(filtered_dat, Type == "Root")

#interaction model
richness_richness_root_fit1 = aov(log(SpeciesRichness) ~ Inoculation * Water, data = root_dat)
Anova(richness_root_fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(richness_root_fit1)
plot(allEffects(richness_root_fit1))

#additive model 
richness_root_fit2 = aov(log(SpeciesRichness) ~ Inoculation + Water, data = root_dat)
Anova(richness_root_fit2, type = "2")
plot(richness_root_fit2)
plot(allEffects(richness_root_fit2))

## SPECIES RICHNESS: SHOOTS  #################################################

shoot_dat = subset(filtered_dat, Type == "Shoot")

#interaction model
richness_shoot_fit1 = aov(log(SpeciesRichness) ~ Inoculation * Water, data = shoot_dat)
Anova(richness_shoot_fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(richness_shoot_fit1)
plot(allEffects(richness_shoot_fit1))

#additive model 
richness_shoot_fit2 = aov(log(SpeciesRichness) ~ Inoculation + Water, data = shoot_dat)
Anova(richness_shoot_fit2, type = "2")
plot(richness_shoot_fit2)
plot(allEffects(richness_shoot_fit2))

```

```{r}
## OUTLIER ANALYSIS ## 

## TOTAL BIOMASS: ROOTS  #####################################################
bio_root = subset(dat, Type == "Root")
  
#interaction model
root_mass1= aov(WeightGrams ~ Inoculation * Water, data = bio_root)
Anova(root_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate

#additive model
root_mass2 = aov(WeightGrams ~ Inoculation + Water, data = bio_root)
Anova(root_mass2, type = "2")

#plot to check residuals
plot(root_mass1)
plot(root_mass2)

# Studentized residuals
MASS::studres(root_mass1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_dat2 = dat[-c(193), ]

```

```{r}
## OUTLIER ANALYSIS ## 

## TOTAL BIOMASS: SHOOTS #####################################################
#interaction model
shoot_mass1 = aov(WeightGrams ~ Inoculation * Water, data = shoot_dat)
Anova(shoot_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate

#additive model
shoot_mass2 = aov(WeightGrams ~ Inoculation + Water, data = shoot_dat)
Anova(shoot_mass2, type = "2")

#plot to check residuals
plot(shoot_mass1)
plot(shoot_mass2)

# Studentized residuals
MASS::studres(shoot_mass1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_dat3 = dat[-c(182), ]

```


```{r}
## TOTAL BIOMASS: ROOTS  #####################################################
bio_root_dat = subset(filtered_dat2, Type == "Root")
  
#interaction model
root_mass1= aov(log(WeightGrams) ~ Inoculation * Water, data = bio_root_dat)
Anova(root_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(root_mass1, main = "Root")
plot(allEffects(root_mass1))

#additive model
root_mass2 = aov(log(WeightGrams) ~ Inoculation + Water, data = root_dat)
Anova(root_mass2, type = "2")
plot(root_mass2, main = "Root")
plot(allEffects(root_mass2))

## TOTAL BIOMASS: SHOOTS #####################################################
bio_shoot_dat = subset(filtered_dat3, Type == "Shoot")

#interaction model
shoot_mass1 = aov(log(WeightGrams) ~ Inoculation * Water, data = bio_shoot_dat)
Anova(shoot_mass1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(shoot_mass1, main = "Shoot")
plot(allEffects(shoot_mass1))

#additive model
shoot_mass2 = aov(log(WeightGrams) ~ Inoculation + Water, data = shoot_dat)
Anova(shoot_mass2, type = "2")
plot(shoot_mass2, main = "Shoot")
plot(allEffects(shoot_mass2))

```


```{r}
## ROOT:SHOOT RATIO ##########################################################

#load data with root:shoot ratio and total biomass (values calculated in excel)
rs_dat = read_csv("./pips_data/pips_rootshoot_ratios.csv") |>
  mutate(
    Inoculation = as.character(Inoculation),
    Water = as.character(Water),
  )

ggplot(rs_dat, aes(Inoculation, RootShootRatio, fill = Water)) +
  scale_y_log10() +
  geom_boxplot()

#interaction model
rs_fit1 = aov(RootShootRatio ~ Inoculation * Water, data = rs_dat)
Anova(rs_fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(rs_fit1)

#additive model 
rs_fit2 = aov(RootShootRatio ~ Inoculation + Water, data = rs_dat)
Anova(rs_fit2, type = "2")
plot(rs_fit2)

# Studentized residuals
MASS::studres(rs_fit1) |>
  abs() |>
  sort()

#remove the outliers, re-run the analysis
filtered_rs = rs_dat[-c(49), ]

#plot the filtered data to check the spread
ggplot(filtered_rs, aes(RootShootRatio)) +
  facet_grid(Water ~ Inoculation) +
  # scale_x_log10() +
  geom_histogram()

#interaction model
rs_fit1 = aov(log(RootShootRatio) ~ Inoculation * Water, data = filtered_rs)
Anova(rs_fit1, type = "3") # if you have interactions, type-3 sums-of-squares is appropriate
plot(rs_fit1)

shapiro.test(rs_fit1$residuals)

#additive model 
rs_fit2 = aov(log(RootShootRatio) ~ Inoculation + Water, data = filtered_rs)
Anova(rs_fit2, type = "2")
plot(rs_fit2)

shapiro.test(rs_fit2$residuals)

```
